/// Flutter icons Tim_icons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tim_icons
///      fonts:
///       - asset: fonts/Tim_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Tim_icons {
  Tim_icons._();

  static const _kFontFam = 'Tim_icons';
  static const _kFontPkg = null;

  static const IconData i012_ninja = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i013_first_aid_kit = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i016_skip_rope = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i017_katana = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i019_dummy = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i020_kudo = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i021_chishi = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i026_boxing_gloves = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i027_trident = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i028_gym_bag = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i029_kendo = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i030_dohyo = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i031_water_bottle = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i032_geta = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i033_kunai = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i037_bo = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i043_champion_belt = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i044_gum_shield = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i045_punch = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i048_mongkhon = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i001_weight = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i022_gong = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i015_punching_bag = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i018_boxing_helmet = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i014_boxing_ring = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i050_toya = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i007_nunchaku = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i024_spear = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i038_karate = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i046_tatami = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i011_hakama = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i003_fencing_mask = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i006_karate = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i041_kendo = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i047_dojo = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i004_kimono = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i023_black_belt = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i025_muk_yan_yong = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i009_baton = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i036_fan = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i039_medal = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i049_yin_yang_symbol = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i002_wheel = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i034_punching_bag = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i040_shin_guards = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i042_samurai = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i035_kettlebell = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i008_kung_fu = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i005_shuriken = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i010_punch = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
